### ISSUE TITLE
Stopped working month ago

### ISSUE THREAD

**Issue by goyaweb** [irritanterik/homey-tesla.com#1]
Using version 1.1.1. Location and chargelevel control (only ones i use/tested) stopped working.
Log shows this line every 5 minutes:
> error with loading initial location: tracking terminated, will retry in 5 minutes.
> "not_found"

**Comment by irritanterik** [comment]
Hey @goyaweb! Just noticed this issue. Can I contact you for debugging support on this issue?

**Comment by irritanterik** [comment]
solved.
