### ISSUE TITLE
Flows broken / Car missing from devices collum in flow section

### ISSUE THREAD

**Issue by mruiter** [irritanterik/homey-tesla.com#11]
Added the car as Model X 

There is no device card in the flow section devices collum on the left. 
There is a device mobilecard in the devices section and it shows the expected driving state and location.

**Comment by irritanterik** [comment]
Yeah, some preliminary code slipped in the api fix. I'm rewriting pairing for this. For now add all your model X vehicles as model S :).
Can you send me your getVehicles respond in a PM? With that I can tune pairing so a model X is identified as X with right icons and flows.

**Comment by irritanterik** [comment]
Pairing for model X and 3 fixed in new app.
