### ISSUE TITLE
Homey version 2.0...

### ISSUE THREAD

**Issue by skandshus** [irritanterik/homey-tesla.com#12]
Can this app be updated for homey 2.0?

**Comment by irritanterik** [comment]
Hope so. Will upgrade when Homey v2 is a bit more proven tech.

**Comment by prj84** [comment]
Please update app to work with Homey 2.0. My auto heating flows fail after update (and it is -10c here in Norway now) Brrr....

**Comment by prj84** [comment]
I edited my post, I’m not a editor of this app! :-) But really would like an update!

**Comment by irritanterik** [comment]
Sorry guys, my whole house runs on Homey and i'm cautious with installing release candidates/beta's on it. Also, I don't own a Tesla so need to make arrangements to upgrade the app. 
I will have some time available around the holydays and wil decide then to upgrade and debug/fix.

**Comment by skandshus** [comment]
That's alrigth..
we cant have everything right away.. especially when its free.

Let me know if you want to do some debugging.. then i can update MY tesla app on my homey, if its possible to do manually  so u dont have to do it on your own.. 
i can also grant you access to a tesla model s if you need...

**Comment by prj84** [comment]
Thanks Erik! :-)

**Comment by irritanterik** [comment]
I'll keep you all posted! And some help with testing will be appreciated by the community

**Comment by skandshus** [comment]
Sure thing :)

**Comment by skandshus** [comment]
Have you had any time lately? :)

**Comment by irritanterik** [comment]
Hi all, I decided to remove the Tesla apps (and some other apps) from the app store for now. Can 't get the setting screens to work on mobile, will need web API maybe for that, but that is not documented yet. I will focus on getting HTTP Geek app a great experiance. Repos stay online for sideloaders.

The app will keep running on existing installs. I expect to support V2 on a geeky way later on, that will not comply with app store requirements (won't even try to get that reviewed). Pull requests are welcome though if you're a coder.

**Comment by skandshus** [comment]
Damn I'm not a cider and I am on honey version 2.0.. I was so desperately hoping to have it work..:(
Is it a real pain getting it to work in 2.0??

**Comment by skandshus** [comment]
THANK YOU for reopening..
Send me your paypaland and I’ll throw some motivation your way..

**Comment by irritanterik** [comment]
Wait for the update first :).

**Comment by skandshus** [comment]
I though it was already out..
My homey said it automatically updates toV2.0 today or yesterday..:)

**Comment by Genghes** [comment]
Jepp.. Homey 2.0.0 is released. 
No preasure, but please update as fast as possible..  ;) ;)
I cant change/create geofences in v2.0.0

**Comment by skandshus** [comment]
im all excited

**Comment by irritanterik** [comment]
Thanks for your support. I'll elaborate on the process and my approach

Compatibillity issues current version App with Homey V2 and other points of improvement
1. Homey Location API changed, resulting in crash on app install
2. Code has to be ported to SDK v2
3. I'd like to redo the pairing process and ask for account settings in the pair procedure instead of on the settings screen.
4. Setting screen:
  a. The window/space for app settings is drasticly reduced with the mobile only approach. 
  b. I doubt managing geofences will be doable by touch - or will take a lot of time
  c. Debug options are a bit harder: logging functions on old settings screen helped debugging a lot.
5. ModelX and Model3 support is not optimal
6. Pairing process needs a fix, because some cars are now paired using the wrong unique identifier, resulting in broken flows months later.
7. Device screen could be improved, i.e. showing battery status

Approach:
1. I'll convert a 'minimal viable product' to SDK v2 and strip a lot of settings and geofence functions:
 - Fix existing pairing issues
 - Geofences created with pre homey v2.0 settions will keep working
 - No option to add/edit/remove geofences
 - A default geofence 'home' will be created when a clean install is done 
 - Flow cards unchanged
 - All users need to re-pair there cars with this release
2. Adding Model X and Model 3 support
3. Maybe add basic geofence edit functions again in new settings screen.
4. Other improvements

**Comment by skandshus** [comment]
This is SO awesome.
i just got my tesla 1 month ago. and i was eager to try the Homey app just to find out it didnt work on my homey 2.0 :) SO now i am waiting.
Do you need a login to test with?

**Comment by irritanterik** [comment]
Hi all, i've working on it now. The account login will be moved to the pairing procedure (its now in the app settings):
![image](https://user-images.githubusercontent.com/15232724/51493461-b7b6b000-1db5-11e9-982f-51b350199952.png)

I basicly need to rewrite the entire app, so next step is to get some basic functionallity working after pairing and release that as a beta app.

**Comment by skandshus** [comment]
Let me know if/when you need a test login.. I got a car plugged in the whole night so you can do what you want.. as long as you don’t sound the horn in the middle of the night..:) light, air con , pre heat and whatever :)

**Comment by irritanterik** [comment]
Thanks, i'm having access to a tesla account now for development. Looking for someone with more than one tesla on the same account though..

**Comment by skandshus** [comment]
Oooh.. yeah can’t help you there.. got no more money in the bank :-)

**Comment by joeripeet** [comment]
ah ok! In one account I cannot help you!

**Comment by zsetefan** [comment]
Hi Erik,

First thanks for the development of this app. It worked great before Homey 2.0. If you need support for testing, you can count me in (Model x).

Kind regards,
Stephen

**Comment by irritanterik** [comment]
Hi all, yesterday I added polling for battery status:
![image](https://user-images.githubusercontent.com/15232724/51589155-7540c080-1ee6-11e9-8ee9-70f1d2d9c9a3.png)

Now a few questions. I don't want the app to drain batteries. What do you think of:
- setting to disable all polling (only get location actively with flow action card)
- setting to enable location polling 
- setting with location polling when not driving (like every 120 seconds; polling when not driving is needed to determine if you left a geofence)
- setting with location polling when driving (like every 20 seconds; you want this to be more precise to get triggers for geofence enter and exit in time)
- setting to enable battery polling
- setting with battery polling interval when not driving
(battery will be polled during driving with interval based on drive polling settings)

As said before, geofence functionality in the first release will be limmited. Creating a mobile compatible user interface for drawing geofences will cost me a lot of time, so look to this after other core functions are working.

**Comment by skandshus** [comment]
All that sounds GREAT... 
I can charge at home and also at work so battery drain is not anything I’m concerned with... :)

**Comment by prj84** [comment]
Sounds great! :-) Setting charge limit, start/stop charging. Set temp and start/stop climate is the most important on my part! :-)

**Comment by rasssta** [comment]
+1 on temp/climate!

**Comment by zsetefan** [comment]
Hi Erik,
Proposition for polling sounds great. Why not leave the intervals user variable. Most drivers won't mind the little battery drain. About the geofencing, if you can set geofencing without a user interface (graphical) where you take the actual position of your car as the starting point and let users decide for a square or circle with the radius (distance) as user input (for example in meters), everyone can set the perfect radius for themselves after testing 1 or 2 times.

**Comment by irritanterik** [comment]
@prj84 @rasssta Like in the old app with flow action cards, or also directly on the devices screen in the Homey App?
@zsetefan Not entirely clear in my post, but all interval values can be adjusted by user. Thanks for your suggestion for geofence-creation.

**Comment by rasssta** [comment]
I have never used the old app. Flow is the most important .Devices screen is nice but not a must since you can always do virtual devices and work around the problem but it's of course better with native support! :)

**Comment by prj84** [comment]
@prj84 @rasssta Like in the old app with flow action cards, or also directly on the devices screen in the Homey App?
@zsetefan Not entirely clear in my post, but all interval values can be adjusted by user. Thanks for your suggestion for geofence-creation.

Flow cards is the most important. But if it is possible on the device screen as well it would be really nice! (No need for the Tesla app anymore! 😂)

**Comment by irritanterik** [comment]
Hey guys, got the location tracking and battery polling mechanism working now. I'm now able to (re)build flow triggers/actions/etc. Expect to commit a first beta version later this week.

**Comment by skandshus** [comment]
Best news in 2019 so far!

**Comment by Genghes** [comment]
Love it.. Please let us know if you need anything.

**Comment by prj84** [comment]
Fantastic! Looking forward to it!

**Comment by bliekp** [comment]
Can't wait! I'll buy you a beer! :)

**Comment by zsetefan** [comment]
Off topic (sorry) but a little tip for Tesla/ Homey owners. If you buy a AEX-701 klikaanklikuit range extender, you can train homey to communicate with your Tesla with 3 different signals from the homelink system. Very handy if you have z-wave operated gates and garage doors not compatible with homelink.

**Comment by skandshus** [comment]
How do I download the alpha? Is it in the App Store?

**Comment by irritanterik** [comment]
@skandshus It will be when icons and basic geofence functions are ready. For now you'll have to 'sideload' the app. Its a bit techy: https://www.youtube.com/watch?v=lRZLvhF2sfk

**Comment by prj84** [comment]
Tested and works perfect! :-) My Homey is complete again! Thanks Erik!

**Comment by prj84** [comment]
Condision card Aircon On/off doesn't work for me. It starts new flows to start the aircon even if it is on. Other then that no other problems. 

Actions tested:
Aircon on/off,  Charge % og start/stop charging works fine :-)

**Comment by mifhockey** [comment]
Any plans on supporting Tesla Model 3? If yes, when?

**Comment by irritanterik** [comment]
Can anyone else confirm this bug? 

> Condision card Aircon On/off doesn't work for me.

**Comment by skandshus** [comment]
I haven't gotten to manually side load the app.. but I did push a few € your way to buy some beers.. :)

**Comment by prj84** [comment]
Just to describe what I have tested with condision card Aircon On/off.
I have 5 flows that starts at different times depending on outside temperature. I have set a condision in all flows that is should not start if aircon is on. But even if first flow starts the aircon all other flows do the same. So no I get 5 push notifications with Aircon had started.

**Comment by irritanterik** [comment]
Beta version is submitted to the app store and now awaits review by Athom (could take them a few days).

**Comment by skandshus** [comment]
Great news!!!!!!

**Comment by irritanterik** [comment]
Hi all. The beta app (v 2.0.0) is now available in the app store.
You'll need to re add your car and fix flows. 
If you had my previous version installed direct from github, you'll need to deinstall this version manual.

For now i'm closing this issue. Please report new bugs and suggestions in separate issues on this repro. If the beta runs well, i'll promote it to stable in about 2 weeks.

Everybody thanks for the support. I've again had a lot of fun programming with your great EVs!

**Comment by goyaweb** [comment]
I can't seem to find the default "Home" geofence nor any existing geofences I had created in v1. How can I configure / enable / find that?

> Geofences created with pre homey v2.0 settions will keep working
> A default geofence 'home' will be created when a clean install is done

**Comment by irritanterik** [comment]
This version does not support geofencing. There is a capabillity instead with the actual distance to homey.

**Comment by irritanterik** [comment]
Ps: please create seperate issues from now on to improve tracabillity

**Comment by joeripeet** [comment]
Hi,

Cannot login...

[image1.png]

Met vriendelijke groet,

Joeri Peeters | Your Business Online
Verstuurd vanaf mijn iPhone

Op 11 feb. 2019 om 16:30 heeft Erik van Dongen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Ps: please create seperate issues from now on to improve tracabillity

**Comment by goyaweb** [comment]
I didn't realize "afstand" was "afstand to homey". I find the naming confusing.

**Comment by irritanterik** [comment]
@joeripeet please log a separate issue with the screenshot
