### ISSUE TITLE
‘Stops Moving’ does not trigger

### ISSUE THREAD

**Issue by Genghes** [irritanterik/homey-tesla.com#14]
App v2.0.0
‘Starts Moving’ works fine, but I never get the ‘Stops Moving’ trigger to fire.

**Comment by irritanterik** [comment]
I'll investigate. Have you changed the default settings for intervals and timing on the device settings?

**Comment by Genghes** [comment]
No, I have not changed the defaults. 

Track Loc : Yes
Save last.. : No 
Loc Track Interval during driving: 60
When parked: 120
Poll batt: Yes
Batt poll int. : 20

min mov triggers: 10
min dist trav.. : 1

**Comment by irritanterik** [comment]
My stoped card works ok, but running on dev 2.1.0 version. Have you created this flow after installing v 2.0.0?

**Comment by Genghes** [comment]
Yes. All cards from 1.0.5 got errors when i upgraded, så all flows recreated.
And its a simple test flow: When stopped send notification with start/stop and distance

**Comment by Genghes** [comment]
Works perfectly again..
Thank you..
