### ISSUE TITLE
cannot enter my tesla account

### ISSUE THREAD

**Issue by gompie23** [irritanterik/homey-tesla.com#17]
app installed V2  When i want to configure i cant enter my tesla account.
Deleted and reinstall doesn't help

**Comment by irritanterik** [comment]
Hi! Did you installed the beta version from the app store? Account settings are now integrated in the device pairing process.

**Comment by gompie23** [comment]
Ja Erik,
Aal ik probeer de app te configureren dan krijg ik het zoekrondje en die gaat niet meer weg

Van: Erik van Dongen <notifications@github.com>
Verzonden: vrijdag 29 maart 2019 09:52
Aan: irritanterik/homey-tesla.com <homey-tesla.com@noreply.github.com>
CC: Gerben Plantinga <gerben@9205ga.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [irritanterik/homey-tesla.com] cannot enter my tesla account (#17)


Hi! Did you installed the beta version from the app store? Account settings are now integrated in the device pairing process.

**Comment by irritanterik** [comment]
Het toevoegen/koppelen is gewijzigd ten opzichte van V1. Je kan nu gelijk
een device toevoegen, daarna wordt gevraagd om je accountgegevens. Je hoeft
dus niet naar de app settings.
Als het zo nog steeds niet lukt, kan je dan een schermprintje meesturen?

Op vr 29 mrt. 2019 09:58 schreef gompie23 <notifications@github.com>:

**Comment by gompie23** [comment]
Snap niet wat je bedoeld

[image1.jpeg]

Als ik hier configureren app doe blijf hij hangen
Ik kan verder niets omdat ik nog niets in een flow kan toevoegen

Gerben Plantinga

Freelance Systeembeheerder Microsoft specialist

9205GA.nl<http://9205ga.nl/>

p:

0512 540121<tel:0512%20540121>  m: 06 811 522 90<tel:06%20811%20522%2090>

a:

Waterland 17, 9205GA Drachten

w:

www.9205ga.nl<http://www.9205ga.nl/>  e: gerben@9205ga.nl<mailto:gerben@9205ga.nl>




Op 30 mrt. 2019 om 08:34 heeft Erik van Dongen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Het toevoegen/koppelen is gewijzigd ten opzichte van V1. Je kan nu gelijk
een device toevoegen, daarna wordt gevraagd om je accountgegevens. Je hoeft
dus niet naar de app settings.
Als het zo nog steeds niet lukt, kan je dan een schermprintje meesturen?

Op vr 29 mrt. 2019 09:58 schreef gompie23 <notifications@github.com<mailto:notifications@github.com>>:

**Comment by irritanterik** [comment]
Sorry,  je schermprint is niet doorgekomen op github.

**Comment by irritanterik** [comment]
In Homey moet je onder 'Apparaten' eerst een nieuwe Tesla toevoegen. Daarbij worden je accountgegevens gevraagd. Hierna kan je flows maken.

![Screenshot_20190330-115115_Homey](https://user-images.githubusercontent.com/15232724/55275155-467a0880-52e2-11e9-99ed-a2cab98908a5.jpg)

**Comment by gompie23** [comment]
??



Gerben Plantinga

Freelance Systeembeheerder Microsoft specialist

9205GA.nl<http://9205ga.nl/>

p:

0512 540121<tel:0512%20540121>  m: 06 811 522 90<tel:06%20811%20522%2090>

a:

Waterland 17, 9205GA Drachten

w:

www.9205ga.nl<http://www.9205ga.nl/>  e: gerben@9205ga.nl<mailto:gerben@9205ga.nl>




Op 30 mrt. 2019 om 11:53 heeft Erik van Dongen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Closed #17<https://github.com/irritanterik/homey-tesla.com/issues/17>.

**Comment by irritanterik** [comment]
I misclicked submitting my last comment:)

**Comment by irritanterik** [comment]
@gompie23 Is your issue resolved with my last instruction/screenprint?

**Comment by gompie23** [comment]
Yes, thanks
