### ISSUE TITLE
Model X support?

### ISSUE THREAD

**Issue by gvdijnsen** [irritanterik/homey-tesla.com#2]
Is there any reason this would not work for a Model X? If so, what is needed to add functionality for Tesla Model X?

**Comment by irritanterik** [comment]
Nope. I think it would work.
I would need access to a tesla account and credentials to test this myself.

**Comment by gvdijnsen** [comment]
As Soon as my Tesla has arrived I will test it and report back ;-)

**Comment by mruiter** [comment]
Works perfect on the X
The only problem is the sunroof doesnt open ;)

**Comment by mruiter** [comment]
Now we only need to add the X as a picture when theres a X 2 pair ;)

**Comment by gvdijnsen** [comment]
Indeed this works perfectly for the X although I have a problem since about 4 days which I will report in a separate issue.
