### ISSUE TITLE
Krijg de app niet werkend

### ISSUE THREAD

**Issue by aeolusnl** [irritanterik/homey-tesla.com#25]
Hoi Erik, in de stable version mis ik de knop configure app. In de beta heb ik de knop wel, maar als ik erop klik dan blijft er een wit scherm eindeloos laden. Heb je een tip?

**Comment by irritanterik** [comment]
Heb je eerst je auto als device toegevoegd? Het settingscherm in de beta wil niet laden als er nog geen auto is gekoppeld.

**Comment by aeolusnl** [comment]
Ok dat was het. Ik dacht juist dat je met configure in de app settings de credentials van de auto moest opgeven. Is gelukt nu dank!
