### ISSUE TITLE
Location Tracking failing

### ISSUE THREAD

**Issue by PexJensen** [irritanterik/homey-tesla.com#3]
The location tracking has stopped working a couple off days ago.

This is in the log:

error with loading initial location: tracking terminated, will retry in 5 minutes.
{"error":{"message":"Unexpected token < in JSON at position 0"},"result":"\n\n\n\n
Moved Permanently
\n
The document has moved here.

\n
\n
Apache/2.4.18 (Ubuntu) Server at nominatim.openstreetmap.org Port 80
\n\n"}

**Comment by PexJensen** [comment]
Looks like this is the reason.

https://github.com/openstreetmap/operations/issues/190

**Comment by irritanterik** [comment]
fixed with 8cf38611a5dff19293493ce6d726a9c9ca23feb5 and pending appstore approval
