### ISSUE TITLE
API condition

### ISSUE THREAD

**Issue by BBEHannes** [irritanterik/homey-tesla.com#37]
Not getting a lot of response on the forums (ye ye, maybe I should wait a while more but I am desperate ;)) so maybe someone here can help me.

I am searching for the API condition that allows me to see whether or not the car is currently charging.. can’t seem to find the correct one or use the right condition that goes with it. 

Hope someone can assist.

**Comment by BBEHannes** [comment]
Anyone?

**Comment by Genghes** [comment]
Hi.
I answered by Email the same say, but i see it has not been picked up by Github.

I see there is a condition under API condition: Charging State
This could be used?
If not, there is ‘Charge Rate’ and ‘Charging power’

**Comment by BBEHannes** [comment]
Hi! Thanks a bunch for your thoughts; what would be the right states for this call? A Boolean doesn’t work (tried that) and I do not know what it expects when I simply would like a “yes or no” result..

**Comment by Genghes** [comment]
Simplest method i found was to use 'Charger Power'
This returns the kW the charger is charging with.
So:
API Condition Charger Power Above (number) 1.5

This will be true as long as the car is chareing with more than 1.5kW

**Comment by BBEHannes** [comment]
Tested and this is very workable indeed, thanks a bunch, much appreciated!
