### ISSUE TITLE
Help: get this error message

### ISSUE THREAD

**Issue by aiiDaH** [irritanterik/homey-tesla.com#39]
when trying to install I gett this error message when I run the app
Can someone translate this problem and help me what to do im new to using Terminal at all

Error: Cannot find module 'http.min'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/lib/tesla.js:4:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

--- INFO: com.tesla has been killed ---

**Comment by irritanterik** [comment]
Have you saved the node_modules folder on disk within the app directory? 

https://github.com/irritanterik/homey-tesla.com/tree/master/node_modules

**Comment by aiiDaH** [comment]
@irritanterik 
no idea I just installed it  

npm install
homey app install
homey app run

can you give me a hint on how to do it I have no experience at all with terminal so this is new area for me, I just followed a guide

**Comment by irritanterik** [comment]
You apparently did not downloaded the complete repository.

**Comment by Genghes** [comment]
After starting up Node.js just run the two commands:

npm install point-in-polygon
npm install http.min

Then the app should compile.

**Comment by aiiDaH** [comment]
> After starting up Node.js just run the two commands:
> 
> npm install -g point-in-polygon
> npm install -g http.min
> 
> Then the app should compile.

@Genghes 

im completely new bare with me, how do I start node.js ?

I tried to run the commands directly in terminal on Mac but got error so that was not the way you suggested apparently 

could you please explain further for a slow Swedish man :P

**Comment by Genghes** [comment]
Maybe in Norwegian then?
Lets stick to Englih in here... ;)

I'm noob myselv and om Windows so it might not be exatly like.

On Windows at least you have to install Node.js
Then start up Node.js command prompt
then install homey:
`npm install -g homey`

then log in to homey:
`homey login`
(Will open a web page to log in and accept connection)

then go to the folder of the app.
then run the install for the Tesla dependencies:
`npm install -g http.min`
`npm install -g point-in-polygon`

If you have more than one homey you can try:
`homey list`
This will list all homeys on your account.

`homey select`
This will let you choose the active homey

`homey app run`
This will run the app in the folder you are
But will uninstall it as soon as you exit it (ctrl+c)

`homey app install`
Will install it as a 'normal' app in your homey.

As I said, this could be a bit different om a mac.

**Comment by aiiDaH** [comment]
@Genghes 
@irritanterik 

looks almost as on Mac then I think

I did 

npm install -g homey - this gives me error when I do now, but I have installed other apps so homey is installed?
homey login

and i downloaded the app via zip, unpacked it and put on desktop and renamed it to Tesla because name was so long

started terminal wrote cd desktop/Tesla  
then
npm install -g http.min
npm install -g point-in-polygon
<img width="702" alt="Skärmavbild 2020-03-26 kl  22 50 52" src="https://user-images.githubusercontent.com/16090895/77700334-41629e80-6fb4-11ea-8377-e628d2a49521.png">

**Comment by Genghes** [comment]
You are missing the -g in the install commands.

And not sure, but I think there is a naming convention so please keep the folder name.
Make a folder direckly under C: (c:\homeyapps) and unpack and work from there.
