### ISSUE TITLE
Trigger on door lock/unlock?

### ISSUE THREAD

**Issue by Lindhardsen** [irritanterik/homey-tesla.com#6]
I would love to be able to trigger a workflow on the car being unlocked, or the doors being open. 

According to the App description, it seem like you should be able to trigger on any API condition, but I havent been able to figure out how. 
Is this possible? And if not, could you please add this feature?

Background: Apparently I have a couple of times happened to trigger the remote, while leaving the car, resulting in leaving a FW door open in a public parking lot :-(
Also, my kids sometime forget to close the doors when we park at home. 
Being able to trigger on an unlock, and set a timer of, say, 2 minutes, after which I'm alerted, would be really beneficial!

**Comment by PexJensen** [comment]
You could trigger a new flow, when your Tesla stops moving Set a delay on 2 minuttes.

In the new flow you should be able to check on the api status and also if the car is not moving.

**Comment by irritanterik** [comment]
Thats indeed the way to go. Direct triggering is not possible, so you need to poll (trigger the flow every x seconds) or check the lock state x minutes after stopping the car.

**Comment by Lindhardsen** [comment]
Seems to work just fine, thanks!
