### ISSUE TITLE
API errors since a few days

### ISSUE THREAD

**Issue by gvdijnsen** [irritanterik/homey-tesla.com#7]
Since a few days the Tesla app has stopped working for me and spits out errors in the logs:

{"error":{"message":"Unexpected token < in JSON at position 0"},"result":"
Our servers are waiting for a supercharger spot..

"}

Apparently this is can be helped by changing some headers as stated in: 
https://teslamotorsclub.com/tmc/threads/error-in-tesla-api.127239/

**Comment by lbink** [comment]
I have the same issue. Right after the Tesla was down for maintenance last week.

**Comment by irritanterik** [comment]
Hi @gvdijnsen @lbink thanks for reporting. I commited a fix based. Can you run the tesla app from this github master and test this fix?

**Comment by PexJensen** [comment]
Hi @irritanterik your fix seems to be working. I can now login again and gets no errors.

**Comment by lbink** [comment]
Hi Erik,

It works again! Thanks.

Buying you a beer as we speak. Cheers.


Met vriendelijke groeten, kind regards,

Leo Bink
BINK ICT B.V.

Laan van Leeuwesteyn 22
2271 HK Voorburg
Leo@Bink.nu<mailto:Leo@Bink.nu>
+31 (0)6 52693859
Bink.nu<http://bink.nu/>
P Think before you print.

**Comment by irritanterik** [comment]
Thanks for your support!
