### ISSUE TITLE
Can't save Tesla Account settings

### ISSUE THREAD

**Issue by boreno** [irritanterik/homey-tesla.com#8]
When I push the Save button, I get the message "settings.account.messages.errorValidation.[object Object]". The account credentials are correct and work when logging in on the website and the Tesla app on iOS (I have checked this at least three times).
I am getting no additional information or logging, even if I have the "Enable debug logging" checkbox ticked.

**Comment by irritanterik** [comment]
Could be related to #7 . Are you able to test this github version of the app?

**Comment by boreno** [comment]
Might be. I can't test the GitHub version, but maybe it could be released
as a beta?
Ludvig

**Comment by irritanterik** [comment]
Beta is pending.

**Comment by irritanterik** [comment]
Beta is available now. Can you test this one for me?

**Comment by boreno** [comment]
I can confirm that the beta works. Thank you!
Ludvig A. Norin

**Comment by irritanterik** [comment]
Ok, i'll push the beta to stable.
